# Generated by Django 3.0.5 on 2020-04-12 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='psot',
            new_name='post',
        ),
    ]
